from __future__ import annotations

from typing import Any, Literal
from pydantic import BaseModel, Field
from enum import StrEnum

# ENUMS

class POICategory(StrEnum):
    RESTAURANT = "restaurant"
    CAFE = "cafe"
    NIGHTLIFE = "nightlife"
    SHOPPING = "shopping"
    TOURIST_ATTRACTION = "tourist_attraction"
    MUSEUM = "museum"
    LANDMARK = "landmark"
    CULTURAL = "cultural"
    PARK = "park"
    ADVENTURE = "adventure"
    ENTERTAINMENT = "entertainment"
    BEACH = "beach"

ANCHOR_CATEGORIES = {
    POICategory.TOURIST_ATTRACTION,
    POICategory.MUSEUM,
    POICategory.LANDMARK,
    POICategory.CULTURAL,
    POICategory.PARK,
    POICategory.ADVENTURE,
    POICategory.ENTERTAINMENT,
    POICategory.BEACH,
}

MEAL_CATEGORIES = {
    POICategory.RESTAURANT,
    POICategory.CAFE,
}

# CLASSES

class ConstraintWP(BaseModel):
    c_id: str # generated by extractor
    constraint: str
    priority: float
    conflicting: bool = False
    c_list: list[str] = Field(default_factory=list)

class Query(BaseModel):
    c_id: str # generated by extractor
    q_id: str  # generated by extractor
    day_number: list[int]
    query: str

class DestinationInfo(BaseModel):
    d_name: str
    overview: str | None = None
    must_see: list[str] = Field(default_factory=list)
    things_to_do: list[str] = Field(default_factory=list)
    travel_tips: list[str] = Field(default_factory=list)
    safety_advice: list[str] = Field(default_factory=list)
    source: str | None = None
    source_url: str | None = None
    raw: dict[str, Any] = Field(default_factory=dict)
class DistanceMetrics(BaseModel):
    pass

class NormalizedInput(BaseModel): # generated by extractor
    d_name: str
    starting_point: str | None = None
    days: int = 3
    is_international: bool = False
    budget: float | None = None
    max_travel_time_per_day: int = 180
    optimal_unique_categories: list[Literal[
    "tourist_attraction",
    "restaurant",
    "cafe",
    "beach",
    "shopping",
    "nightlife",
    "museum",
    "park",
    "landmark",
    "adventure",
    "cultural",
    "entertainment"
    ]]
    h_constraints: list[ConstraintWP] = Field(default_factory=list)
    s_constraints: list[ConstraintWP] = Field(default_factory=list)
    queries: list[Query] = Field(default_factory=list)

class POI(BaseModel):
    p_id: str
    p_category: POICategory
    p_name: str
    p_lat: float
    p_lon: float
    distance_km: float
    price: float | None = None
    rating: float | None = None
    reviews_count: int | None = None
    score: float | None = None
    tags: list[str] = Field(default_factory=list)
    raw: dict[str, Any] = Field(default_factory=dict)

class Anchor(BaseModel):
    a_id: str
    a_category: POICategory
    a_name: str
    a_lat: float
    a_lon: float
    zoom: int
    day: int
    budget: float | None = None
    timeslot: Literal[
        "morning",
        "afternoon",
        "evening",
        "night",
    ]
    nearby_poi_count: int | None = None
    score_breakdown: dict[str, float] = Field(default_factory=dict)

    poi: POI

class ScoreBreakdown(BaseModel):
    distance_score: float = 0.0
    preference_score: float = 0.0
    budget_score: float = 0.0
    popularity_score: float = 0.0
    diversity_score: float = 0.0
    fatigue_score: float = 0.0
    routing_score: float = 0.0
    constraint_score: float = 0.0
    temporal_score: float = 0.0
    weather_score: float = 0.0
    safety_score: float = 0.0
    novelty_score: float = 0.0

class Score(BaseModel):
    final_score: float = 0.0
    normalized_score: float = 0.0
    breakdown: ScoreBreakdown = Field(
        default_factory=ScoreBreakdown
    )
    penalties: list[str] = Field(default_factory=list)
    bonuses: list[str] = Field(default_factory=list)
    confidence: float = 0.0

class GlobalState(BaseModel):
    i_id: str
    u_id: str
    d_lat: float | None = None
    d_lon: float | None = None
    s_lat: float | None = None
    s_lon: float | None = None
    normalizedinput: NormalizedInput
    destination_info: DestinationInfo | None = None
    resolved_conflicts: list[str] = Field(default_factory=list)
    anchors: list[Anchor] = Field(default_factory=list)
    remaining_budget: float | None = None 
    travel_distance_km: float | None = None

class Log(BaseModel):
    selected_pois: list[POI]
    rejected_pois: list[POI]
    global_state: GlobalState
    itinerary: dict[str, float] = Field(default_factory=dict)
